name: expiry_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/EEEE.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/images/EEEE.png"

  windows:
    generate: true
    image_path: "assets/images/EEEE.png"

  macos:
    generate: true
    image_path: "assets/images/EEEE.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/